version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn serve
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
      - /var/www/app/dist
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
